# Generated by Django 4.2.6 on 2023-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hairdresser',
            name='specialization',
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='specialization',
            field=models.ManyToManyField(to='reservations.specialization'),
        ),
    ]
