# Generated by Django 4.2.6 on 2023-11-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_specialization_remove_hairdresser_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('M', 'Fryzjer męski'), ('F', 'Fryzjer damski'), ('S', 'Stylista')], max_length=2, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='specialization',
            field=models.ManyToManyField(to='reservations.specializationchoice', verbose_name='specializations'),
        ),
    ]
