# Generated by Django 4.2.6 on 2023-11-04 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_specializationchoice_delete_specialization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 31, 25, 978361, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.service'),
        ),
    ]
