# Generated by Django 4.2.6 on 2023-11-19 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
